name: Publish Package to NPM

on:
  release:
    types: [published]
  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        # Ensure we do a clean install based on package-lock.json
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          # This token should be saved in GitHub Repository Secrets as NPM_TOKEN
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
